apiVersion: v1
kind: Service
metadata:
  name: llama-nomic-embed-text
  namespace: embeddings
spec:
  selector:
    app.kubernetes.io/name: llama-nomic-embed-text
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
