apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: actions-act-runner
  namespace: gitea
spec:
  template:
    spec:
      initContainers:
        - name: init-perms
          image: busybox:1.37.0
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -c
            - chown -R 1000:1000 /data
          volumeMounts:
            - name: data-act-runner
              mountPath: /data
        - name: dind
          securityContext:
            appArmorProfile:
              type: Unconfined
            seccompProfile:
              type: Unconfined
          livenessProbe:
            exec:
              command:
                - /usr/bin/test
                - -S
                - /var/run/user/1000/docker.sock
          startupProbe:
            exec:
              command:
                - /usr/bin/test
                - -S
                - /var/run/user/1000/docker.sock
      containers:
        - name: act-runner
          securityContext:
            appArmorProfile:
              type: Unconfined
            seccompProfile:
              type: Unconfined
          env:
            - name: DOCKER_HOST
              value: unix:///var/run/user/1000/docker.sock
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run
