namespace: gitea

# Provision gitea-actions statefulset, we should end up with 2 runners.
enabled: true

# Provisioning secret -- see readme to create this
existingSecret: gitea-actions-secret
existingSecretKey: GITEA_ACTIONS_TOKEN
giteaRootURL: http://gitea-http.gitea.svc.cluster.local:3000/

statefulset:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  actRunner:
    # https://hub.docker.com/r/gitea/act_runner/tags
    # renovate: datasource=gitea-releases depname=gitea/act_runner versioning=docker
    tag: 0.6.0
    # By default, the helm chart does not populate the labels section of the runner config.
    # This means all jobs start in a bare image without the necessary tools.
    config: |
      log:
        level: debug
      cache:
        enabled: false
      runner:
        labels:
          - "ubuntu-latest:docker://gitea/runner-images:ubuntu-latest"
          - "ubuntu-22.04:docker://gitea/runner-images:ubuntu-22.04"
          - "ubuntu-20.04:docker://gitea/runner-images:ubuntu-20.04"
      container:
        require_docker: true
        docker_timeout: 300s
      valid_volumes:
        - '**'
  dind:
    rootless: true
    # renovate: datasource=github-releases depname=moby/moby versioning=docker
    tag: 28.4.0-dind-rootless

preExtraInitContainers:
  - name: init-perms
    image: busybox:1.37.0
    securityContext:
      runAsUser: 0
    command:
      - sh
      - -c
      - chown -R 1000:1000 /data
    volumeMounts:
      - name: data-act-runner
        mountPath: /data

global:
  storageClass: ""
