apiVersion: route53.aws.crossplane.io/v1alpha1
kind: ResourceRecordSet
metadata:
  name: crobceratops-direct-aaaa.ryanbeales.com
  annotations:
    crossplane.io/external-name: crobceratops.ryanbeales.com.
spec:
  forProvider:
    resourceRecords:
      - value: 2604:3d08:7583:3800::fca9
    type: AAAA
    ttl: 300
    zoneId: Z2AOZQ8V4DDJEY
