apiVersion: route53.aws.crossplane.io/v1alpha1
kind: ResourceRecordSet
metadata:
  name: crobasaurusrex-direct-aaaa.ryanbeales.com
  annotations:
    crossplane.io/external-name: crobasaurusrex.ryanbeales.com.
spec:
  forProvider:
    resourceRecords:
      - value: 2604:3d08:7583:3800:1ac0:4dff:fe04:55ff
    type: AAAA
    ttl: 300
    zoneId: Z2AOZQ8V4DDJEY
