apiVersion: route53.aws.crossplane.io/v1alpha1
kind: ResourceRecordSet
metadata:
  name: croblodocus-direct-aaaa.ryanbeales.com
  annotations:
    crossplane.io/external-name: croblodocus.ryanbeales.com.
spec:
  forProvider:
    resourceRecords:
      - value: 2001:569:5b07:c700:52e0:85ff:fe85:c118
    type: AAAA
    ttl: 300
    zoneId: Z2AOZQ8V4DDJEY
