apiVersion: route53.aws.crossplane.io/v1alpha1
kind: ResourceRecordSet
metadata:
  name: wildcard-aaaa.crobasaurusrex.ryanbeales.com
  annotations:
    crossplane.io/external-name: '*.crobasaurusrex.ryanbeales.com.'
spec:
  forProvider:
    resourceRecords:
      - value: 2604:3d08:7583:3800::31e2
    type: AAAA
    ttl: 300
    zoneId: Z2AOZQ8V4DDJEY
