apiVersion: route53.aws.crossplane.io/v1alpha1
kind: ResourceRecordSet
metadata:
  name: router-aaaa.ryanbeales.com
  annotations:
    crossplane.io/external-name: router.ryanbeales.com.
spec:
  forProvider:
    resourceRecords:
      - value: 2604:3d08:7583:3800::1
    type: AAAA
    ttl: 300
    zoneId: Z2AOZQ8V4DDJEY
