apiVersion: route53.aws.crossplane.io/v1alpha1
kind: ResourceRecordSet
metadata:
  name: router-aaaa.ryanbeales.com
  annotations:
    crossplane.io/external-name: router.ryanbeales.com.
spec:
  forProvider:
    resourceRecords:
      - value: 2001:569:5b07:c700:aab8:e0ff:fe06:c49d
    type: AAAA
    ttl: 300
    zoneId: Z2AOZQ8V4DDJEY
