apiVersion: route53.aws.crossplane.io/v1alpha1
kind: ResourceRecordSet
metadata:
  name: ryanbeales.com-ses-verification
  annotations:
    crossplane.io/external-name: ryanbeales.com
spec:
  forProvider:
    type: TXT
    ttl: 300
    resourceRecords:
      - value: '"Oa/kZ7NrYlzLk+hZYUpb1wS8W2sg0edxSEROjsUSKks="'
    zoneId: Z2AOZQ8V4DDJEY
