apiVersion: route53.aws.crossplane.io/v1alpha1
kind: ResourceRecordSet
metadata:
  name: wg-aaaa.ryanbeales.com
  annotations:
    crossplane.io/external-name: wg.ryanbeales.com.
spec:
  forProvider:
    resourceRecords:
      - value: 2001:569:5b07:c700:e95a:9979:60b3:1e84
    type: AAAA
    ttl: 300
    zoneId: Z2AOZQ8V4DDJEY
