apiVersion: route53.aws.crossplane.io/v1alpha1
kind: ResourceRecordSet
metadata:
  name: wg-aaaa.ryanbeales.com
  annotations:
    crossplane.io/external-name: wg.ryanbeales.com.
spec:
  forProvider:
    resourceRecords:
      - value: 2604:3d08:7583:3800:58b0:5a87:7e90:28f9
    type: AAAA
    ttl: 300
    zoneId: Z2AOZQ8V4DDJEY
