apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama-large
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: ai-services/ollama-large
    repoURL: https://github.com/ryanbeales/personal-k8s-config.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
