apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openclaw

helmCharts:
  - name: openclaw
    repo: "https://serhanekicii.github.io/openclaw-helm"
    version: 1.5.15
    releaseName: openclaw
    namespace: openclaw
    valuesFile: values.yaml

resources:
  - namespace.yaml
  - httproute.yaml
