apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nomic-embed-text-nfs-pvc
  namespace: embeddings
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: crobasaurusrex-nfs
