resources:
- https://github.com/kubernetes-sigs/node-feature-discovery/deployment/overlays/default?ref=v0.18.3
- usb-devices-rules.yaml

patches:
  - target:
      kind: DaemonSet
      name: nfd-worker
    patch: |
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: nfd-worker
      spec:
        template:
          spec:
            tolerations:
              - operator: Exists