apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: usb-devices
  namespace: node-feature-discovery
spec:
  rules:
    - name: "aeotec-zstick"
      labels:
        "feature.node.kubernetes.io/usb-aeotec-zstick": "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            vendor: {op: In, value: ["0658"]}
            device: {op: In, value: ["0200"]}
    - name: "biqu-b1"
      labels:
        "feature.node.kubernetes.io/usb-biqu-b1": "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            vendor: {op: In, value: ["1d50"]}
            device: {op: In, value: ["6029"]}
