apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  namespace: litellm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: litellm
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: litellm
    spec:
      containers:
        - name: litellm
          # renovate: datasource=docker depname=ghcr.io/berriai/litellm versioning=loose
          image: ghcr.io/berriai/litellm:main-latest
          args:
            - "--config"
            - "/app/config.yaml"
            - "--port"
            - "4000"
          ports:
            - name: http
              containerPort: 4000
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: litellm-config
