apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memos-data-pvc
  namespace: memos
  labels:
    app.kubernetes.io/name: memos
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: crobasaurusrex-nfs
  resources:
    requests:
      storage: 10Gi
