apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-gemma4-e4b-local-pvc
  namespace: llama
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 32Gi
