apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./daemonset.yaml
configMapGenerator:
  - name: nvidia-mismatch-rebooter-script
    files:
      - check-mismatch.sh
generatorOptions:
  disableNameSuffixHash: true
