apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
spec:
  template:
    spec:
      volumes:
        - name: patch-work
          emptyDir: {}
      initContainers:
        - name: patch-cuda-graphs
          image: ghcr.io/blakeblackshear/frigate:0.17.2-tensorrt
          command: ["/bin/sh", "-c"]
          args:
            - "cp /opt/frigate/frigate/detectors/detection_runners.py /work/runners.py && sed -i 's/CudaGraphRunner.is_model_supported/False and CudaGraphRunner.is_model_supported/g' /work/runners.py"
          volumeMounts:
            - name: patch-work
              mountPath: /work
      containers:
        - name: frigate
          volumeMounts:
            - name: patch-work
              mountPath: /opt/frigate/frigate/detectors/detection_runners.py
              subPath: runners.py
