apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frigate
  namespace: frigate
  labels:
    app.kubernetes.io/instance: frigate
    app.kubernetes.io/name: frigate
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: frigate
      app.kubernetes.io/name: frigate
  endpoints:
    - port: http
      path: /api/metrics
      interval: 15s
