apiVersion: v1
kind: Service
metadata:
  name: klipper-service
  namespace: klipper
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: klipper
    app.kubernetes.io/component: core
  ports:
    - name: http
      port: 7125
      targetPort: 7125
