apiVersion: apps/v1
kind: Deployment
metadata:
  name: klipper
  namespace: klipper
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: klipper
      app.kubernetes.io/component: core
  template:
    metadata:
      labels:
        app.kubernetes.io/name: klipper
        app.kubernetes.io/component: core
    spec:
      nodeSelector:
        feature.node.kubernetes.io/usb-biqu-b1: "true"
      volumes:
        - name: klipper-pvc
          persistentVolumeClaim:
            claimName: klipper-pvc
        - name: klipper-config
          configMap:
            name: klipper-config
        - name: ttyacm0
          hostPath:
            path: /dev/ttyACM0
      containers:
        - name: klipper
          # renovate: datasource=docker depname=mkuf/klipper versioning=semver
          image: mkuf/klipper:latest
          securityContext:
            privileged: true
          env:
            - name: HOME
              value: /home/klippy
          args:
            - /home/klippy/printer_data/config/printer.cfg
            - -a
            - /home/klippy/printer_data/comms/klippy.sock
            - -l
            - /home/klippy/printer_data/logs/klippy.log
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
            - mountPath: /home/klippy/printer_data
              name: klipper-pvc
            - mountPath: /home/klippy/printer_data/config/printer.cfg
              name: klipper-config
              subPath: klipper.cfg
            - mountPath: /dev/ttyACM0
              name: ttyacm0
