apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-gemma4-12b-nfs-pvc
  namespace: llama
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: crobasaurusrex-nfs
  resources:
    requests:
      storage: 32Gi
