apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omnivoice-nfs-pvc
  labels:
    app: omnivoice
  namespace: omnivoice
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: crobasaurusrex-nfs
  resources:
    requests:
      storage: 10Gi
