apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-bonsai-2-27b-1bit-nfs-pvc
  namespace: llama
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: crobasaurusrex-nfs
  resources:
    requests:
      storage: 256Gi
