apiVersion: v1
kind: Service
metadata:
  name: decision-proxy
  namespace: decision-proxy
  labels:
    app.kubernetes.io/name: decision-proxy
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app.kubernetes.io/name: decision-proxy
