apiVersion: ses.aws.upbound.io/v1beta1
kind: DomainIdentity
metadata:
  name: ryanbeales.com
spec:
  forProvider:
    domain: ryanbeales.com
    region: eu-west-2
  providerConfigRef:
    name: upbound-aws-default
