apiVersion: iam.aws.upbound.io/v1beta1
kind: User
metadata:
  name: ryanbeales-email-forwarder
  namespace: ryanbeales-com
spec:
  forProvider: {}
  providerConfigRef:
    name: upbound-aws-default
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: AccessKey
metadata:
  name: ryanbeales-email-forwarder-key
  namespace: ryanbeales-com
spec:
  forProvider:
    userRef:
      name: ryanbeales-email-forwarder
  writeConnectionSecretToRef:
    name: ryanbeales-email-forwarder-creds
    namespace: ryanbeales-com
  providerConfigRef:
    name: upbound-aws-default
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: ryanbeales-email-forwarder-policy
  namespace: ryanbeales-com
spec:
  forProvider:
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "s3:GetObject",
              "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::ryanbeales.com-mx/*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "sqs:ReceiveMessage",
              "sqs:DeleteMessage",
              "sqs:GetQueueAttributes"
            ],
            "Resource": "arn:aws:sqs:us-west-2:645775182778:ryanbeales-com-ses-forwarder"
          },
          {
            "Effect": "Allow",
            "Action": "ses:SendRawEmail",
            "Resource": "*"
          }
        ]
      }
  providerConfigRef:
    name: upbound-aws-default
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: UserPolicyAttachment
metadata:
  name: ryanbeales-email-forwarder-attachment
  namespace: ryanbeales-com
spec:
  forProvider:
    userRef:
      name: ryanbeales-email-forwarder
    policyArnRef:
      name: ryanbeales-email-forwarder-policy
  providerConfigRef:
    name: upbound-aws-default
