apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: hermes-backend-traffic-policy
  namespace: hermes
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: hermes-webui-route
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: hermes-route
  timeout:
    http:
      requestTimeout: 0s
      streamIdleTimeout: 0s
      maxStreamDuration: 0s
