apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-nfs-pvc
  labels:
    app: hermes
  namespace: hermes
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: crobasaurusrex-nfs
  resources:
    requests:
      storage: 2Gi
