apiVersion: v1
kind: Service
metadata:
  name: qwen-coder-7b
  namespace: qwen-coder
spec:
  selector:
    app.kubernetes.io/name: qwen-coder-7b
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
