apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: opnsense-config
  namespace: crossplane-system
spec:
  forProvider:
    source: Inline
    initArgs:
      - "-upgrade"
    module: |

      variable "opnsense_api_key" {
        type      = string
        sensitive = true
      }

      variable "opnsense_api_secret" {
        type      = string
        sensitive = true
      }

      terraform {
        required_providers {
          opnsense = {
            source  = "browningluke/opnsense"
            version = "~> 0.22.0"
          }
        }
      }

      provider "opnsense" {
        uri            = "https://10.0.0.1"
        api_key        = var.opnsense_api_key
        api_secret     = var.opnsense_api_secret
        allow_insecure = true
      }

      # Kea DHCP Subnet LAN configuration
      resource "opnsense_kea_dhcpv4_subnet" "lan" {
        subnet      = "10.0.0.0/24"
        description = "LAN Subnet managed via Crossplane Terraform"
        routers     = ["10.0.0.1"]
        dns_servers = ["10.0.0.1"]
      }
      resource "opnsense_kea_dhcpv4_reservation" "res_00-e1-00-00-17-b2" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.43"
        mac_address = "00:e1:00:00:17:b2"
        description = "Migrated 00:e1:00:00:17:b2"
      }

      resource "opnsense_kea_dhcpv4_reservation" "eap615-wall-1c-61-b4-37-44-2e" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.61"
        mac_address = "1c:61:b4:37:44:2e"
        description = "Migrated EAP615-Wall-1C-61-B4-37-44-2E"
      }

      resource "opnsense_kea_dhcpv4_reservation" "eap615-wall-1c-61-b4-37-54-14" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.38"
        mac_address = "1c:61:b4:37:54:14"
        description = "Migrated EAP615-Wall-1C-61-B4-37-54-14"
      }

      resource "opnsense_kea_dhcpv4_reservation" "res_04-7c-16-8a-be-65" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.139"
        mac_address = "04:7c:16:8a:be:65"
        description = "Migrated 04:7C:16:8A:BE:65"
      }

      resource "opnsense_kea_dhcpv4_reservation" "c3524224683391" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.90"
        mac_address = "04:57:47:9d:c6:21"
        description = "Migrated C3524224683391"
      }

      resource "opnsense_kea_dhcpv4_reservation" "bose-home-speaker-300" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.25"
        mac_address = "4c:87:5d:bc:85:fe"
        description = "Migrated Bose-Home-Speaker-300"
      }

      resource "opnsense_kea_dhcpv4_reservation" "reocam" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.153"
        mac_address = "5c:c3:36:4c:f8:ea"
        description = "Migrated reocam"
      }

      resource "opnsense_kea_dhcpv4_reservation" "res_5e-bb-f6-9e-ee-fa" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.191"
        mac_address = "5e:bb:f6:9e:ee:fa"
        description = "Migrated 5e:bb:f6:9e:ee:fa"
      }

      resource "opnsense_kea_dhcpv4_reservation" "ryan-s-s26-ultra-107" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.56"
        mac_address = "6e:25:d6:8d:cd:e5"
        description = "Migrated Ryan-s-S26-Ultra-107"
      }

      resource "opnsense_kea_dhcpv4_reservation" "macbookair-91" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.184"
        mac_address = "8e:bd:87:08:fc:5e"
        description = "Migrated MacBookAir-91"
      }

      resource "opnsense_kea_dhcpv4_reservation" "amc0910d201f520dfc" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.67"
        mac_address = "9c:8e:cd:3d:9b:be"
        description = "Front camera"
      }

      resource "opnsense_kea_dhcpv4_reservation" "crobasaurusrex" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.59"
        mac_address = "18:c0:4d:04:55:ff"
        description = "crobasaurusrex"
      }

      resource "opnsense_kea_dhcpv4_reservation" "crobtoplite" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.79"
        mac_address = "20:1e:88:d2:f5:b9"
        description = "Migrated crobtoplite"
      }

      resource "opnsense_kea_dhcpv4_reservation" "home-assistant-voice-0a0800" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.233"
        mac_address = "20:f8:3b:0a:08:00"
        description = "Migrated home-assistant-voice-0a0800"
      }

      resource "opnsense_kea_dhcpv4_reservation" "res_30-68-93-22-6b-ee" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.64"
        mac_address = "30:68:93:22:6b:ee"
        description = "Second balcony ep40m"
      }

      resource "opnsense_kea_dhcpv4_reservation" "ep40m" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.237"
        mac_address = "30:68:93:22:63:21"
        description = "Patio"
      }

      resource "opnsense_kea_dhcpv4_reservation" "res_30-68-93-22-66-3f" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.250"
        mac_address = "30:68:93:22:66:3f"
        description = "EP40M balcony"
      }

      resource "opnsense_kea_dhcpv4_reservation" "canona6e40c" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.240"
        mac_address = "34:9f:7b:a6:e4:0c"
        description = "Migrated Canona6e40c"
      }

      resource "opnsense_kea_dhcpv4_reservation" "res_38-f9-f5-0c-6d-85" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.39"
        mac_address = "38:f9:f5:0c:6d:85"
        description = "Migrated 38:f9:f5:0c:6d:85"
      }

      resource "opnsense_kea_dhcpv4_reservation" "crobgamebox" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.80"
        mac_address = "48:45:e6:0b:5b:75"
        description = "Migrated CROBGAMEBOX"
      }

      resource "opnsense_kea_dhcpv4_reservation" "meross-smart-plug-110" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.160"
        mac_address = "48:e1:e9:15:c0:a9"
        description = "Migrated Meross_Smart_Plug-110"
      }

      resource "opnsense_kea_dhcpv4_reservation" "meross-smart-plug" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.196"
        mac_address = "48:e1:e9:15:c0:d1"
        description = "Migrated Meross_Smart_Plug"
      }

      resource "opnsense_kea_dhcpv4_reservation" "res_48-e1-e9-15-d4-3b" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.116"
        mac_address = "48:e1:e9:15:d4:3b"
        description = "Migrated 48:e1:e9:15:d4:3b"
      }

      resource "opnsense_kea_dhcpv4_reservation" "croblodocus" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.126"
        mac_address = "50:e0:85:85:c1:18"
        description = "Migrated croblodocus"
      }

      resource "opnsense_kea_dhcpv4_reservation" "macbookair" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.218"
        mac_address = "56:2b:4c:af:e3:47"
        description = "Migrated MacBookAir"
      }

      resource "opnsense_kea_dhcpv4_reservation" "mac" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.131"
        mac_address = "56:47:7d:94:6a:c7"
        description = "Migrated Mac"
      }

      resource "opnsense_kea_dhcpv4_reservation" "kobo" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.155"
        mac_address = "58:b0:d4:9d:21:dd"
        description = "Migrated kobo"
      }

      resource "opnsense_kea_dhcpv4_reservation" "res_09aa01ac20180af9" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.18"
        mac_address = "64:16:66:27:dd:3a"
        description = "Migrated 09AA01AC20180AF9"
      }

      resource "opnsense_kea_dhcpv4_reservation" "res_74-c2-46-42-d0-e9" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.17"
        mac_address = "74:c2:46:42:d0:e9"
        description = "Migrated 74:c2:46:42:d0:e9"
      }

      resource "opnsense_kea_dhcpv4_reservation" "usw-mini" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.125"
        mac_address = "78:45:58:47:de:89"
        description = "Migrated USW_MINI"
      }

      resource "opnsense_kea_dhcpv4_reservation" "elmde269" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.94"
        mac_address = "84:2f:57:a4:e4:30"
        description = "Migrated ELMDE269"
      }

      resource "opnsense_kea_dhcpv4_reservation" "samsung-range" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.236"
        mac_address = "88:57:1d:25:13:da"
        description = "Migrated Samsung-Range"
      }

      resource "opnsense_kea_dhcpv4_reservation" "crobputer" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.170"
        mac_address = "88:c9:b3:bf:7d:eb"
        description = "Crobputer"
      }

      resource "opnsense_kea_dhcpv4_reservation" "hs103" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.16"
        mac_address = "98:ba:5f:fd:a2:e0"
        description = "Migrated HS103"
      }

      resource "opnsense_kea_dhcpv4_reservation" "hs103_2" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.2"
        mac_address = "98:ba:5f:fd:b9:9d"
        description = "Lava lamp"
      }

      resource "opnsense_kea_dhcpv4_reservation" "aa-93-66-75-a6-74" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.220"
        mac_address = "aa:93:66:75:a6:74"
        description = "Migrated aa:93:66:75:a6:74"
      }

      resource "opnsense_kea_dhcpv4_reservation" "ryan-s-s26-ultra-72" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.244"
        mac_address = "b6:74:df:ed:61:fb"
        description = "Migrated Ryan-s-S26-Ultra-72"
      }

      resource "opnsense_kea_dhcpv4_reservation" "piframe" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.221"
        mac_address = "b8:27:eb:71:90:f2"
        description = "Migrated piframe"
      }

      resource "opnsense_kea_dhcpv4_reservation" "crobceratops-109" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.97"
        mac_address = "bc:f4:d4:40:6f:79"
        description = "Migrated crobceratops-109"
      }

      resource "opnsense_kea_dhcpv4_reservation" "sm-r920" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.148"
        mac_address = "be:82:d8:21:2f:8c"
        description = "Migrated SM-R920"
      }

      resource "opnsense_kea_dhcpv4_reservation" "xbox-112" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.214"
        mac_address = "c4:cb:76:82:e3:c4"
        description = "Migrated XBOX-112"
      }

      resource "opnsense_kea_dhcpv4_reservation" "xbox" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.217"
        mac_address = "c4:cb:76:82:e3:c7"
        description = "Migrated XBOX"
      }

      resource "opnsense_kea_dhcpv4_reservation" "wled-2" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.78"
        mac_address = "c8:c9:a3:66:93:86"
        description = "Migrated wled-2"
      }

      resource "opnsense_kea_dhcpv4_reservation" "wled-wled" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.201"
        mac_address = "c8:c9:a3:66:97:be"
        description = "Migrated wled-WLED"
      }

      resource "opnsense_kea_dhcpv4_reservation" "wled-wled_2" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.232"
        mac_address = "c8:c9:a3:66:98:92"
        description = "wled-3"
      }

      resource "opnsense_kea_dhcpv4_reservation" "kp303" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.208"
        mac_address = "cc:ba:bd:79:c7:03"
        description = "Powerboard"
      }

      resource "opnsense_kea_dhcpv4_reservation" "e0-51-d8-cf-f5-a5" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.34"
        mac_address = "e0:51:d8:cf:f5:a5"
        description = "Migrated e0:51:d8:cf:f5:a5"
      }

      resource "opnsense_kea_dhcpv4_reservation" "macbookair_2" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.216"
        mac_address = "ee:61:ba:fb:73:0d"
        description = "Migrated MacBookAir"
      }

      resource "opnsense_kea_dhcpv4_reservation" "mely" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.215"
        mac_address = "f0:c3:71:dd:d5:c3"
        description = "Migrated Mely"
      }

      resource "opnsense_kea_dhcpv4_reservation" "ryan-s-s26-ultra" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.113"
        mac_address = "f2:e6:66:4e:42:4d"
        description = "Migrated Ryan-s-S26-Ultra"
      }

      resource "opnsense_kea_dhcpv4_reservation" "f8-3b-1d-bd-63-f2" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.219"
        mac_address = "f8:3b:1d:bd:63:f2"
        description = "Migrated f8:3b:1d:bd:63:f2"
      }

      resource "opnsense_kea_dhcpv4_reservation" "ryan-s-s26-ultra-117" {
        subnet_id   = opnsense_kea_dhcpv4_subnet.lan.id
        ip_address  = "10.0.0.40"
        mac_address = "fe:2a:72:c0:de:12"
        description = "Migrated Ryan-s-S26-Ultra-117"
      }


    env:
      - name: TF_VAR_opnsense_api_key
        secretKeyRef:
          namespace: crossplane-system
          name: opnsense-creds
          key: api-key
      - name: TF_VAR_opnsense_api_secret
        secretKeyRef:
          namespace: crossplane-system
          name: opnsense-creds
          key: api-secret

  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: opnsense-workspace-secret