apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-nfs-pvc
  namespace: n8n
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: crobasaurusrex-nfs
  resources:
    requests:
      storage: 10Gi
