apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepseek-harness-nfs-pvc
  namespace: deepseek-harness
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: crobasaurusrex-nfs
  resources:
    requests:
      storage: 10Gi
