apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: immich
  namespace: immich
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: immich
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: immich
      app.kubernetes.io/name: immich
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
