apiVersion: cloudfront.aws.upbound.io/v1beta1
kind: Distribution
metadata:
  name: www.ryanbeales.com
  annotations:
    crossplane.io/external-name: E14YREW8AXYHTR
spec:
  forProvider:
    region: us-east-1
    enabled: true
    httpVersion: http2and3
    defaultRootObject: index.html
    aliases:
      - www.ryanbeales.com
      - ryanbeales.com
    customErrorResponse:
      - errorCode: 403
        responseCode: 404
        responsePagePath: /errors.html
        errorCachingMinTtl: 300
      - errorCode: 404
        responseCode: 404
        responsePagePath: /errors.html
        errorCachingMinTtl: 300
    defaultCacheBehavior:
      - targetOriginId: S3-www.ryanbeales.com
        viewerProtocolPolicy: redirect-to-https
        allowedMethods:
          - GET
          - HEAD
        cachedMethods:
          - GET
          - HEAD
        forwardedValues:
          - queryString: false
            cookies:
              - forward: none
        functionAssociation:
          - eventType: viewer-request
            functionArn: arn:aws:cloudfront::645775182778:function/www-ryanbeales-com-rewrite
    origin:
      - domainName: www.ryanbeales.com.s3.amazonaws.com
        originId: S3-www.ryanbeales.com
        s3OriginConfig:
          - originAccessIdentity: origin-access-identity/cloudfront/E1KRWOIW9XN96T
    viewerCertificate:
      - acmCertificateArn: arn:aws:acm:us-east-1:645775182778:certificate/610c57f4-2e4b-4e0e-8f27-870193446a91
        sslSupportMethod: sni-only
        minimumProtocolVersion: TLSv1.2_2021
    restrictions:
      - geoRestriction:
          - restrictionType: none
  providerConfigRef:
    name: upbound-aws-default
