apiVersion: cloudfront.aws.upbound.io/v1beta1
kind: Function
metadata:
  name: www-ryanbeales-com-rewrite
spec:
  forProvider:
    name: www-ryanbeales-com-rewrite
    runtime: cloudfront-js-1.0
    publish: true
    codeSecretRef:
      name: www-ryanbeales-com-rewrite-code
      namespace: ryanbeales-com
      key: code
    region: us-east-1
