apiVersion: v1
kind: Service
metadata:
  name: ollama-large
  namespace: ollama
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ollama-large
  ports:
    - name: ollama
      port: 11434
      targetPort: 11434
